-- constants.lua

PADDLE_WIDTH   = 10
PADDLE_HEIGHT  = 60
PADDLE_SPEED   = 180

BALL_SIZE      = 10
BALL_SPEED_X   = 240
BALL_SPEED_Y   = 120

WIN_SCORE      = 10

PADDLE_OFFSET_X = 30
SCORE_OFFSET_Y  = 40

MOUSE_SENSITIVITY = 1.0

COLOR_BG = {0, 0, 0}
COLOR_FG = {1, 1, 1}