require('model.serial.init')
require('model.serial.backend_fake')

local function make()
  local b = FakeBackend.new()
  return Serial.new(b), b
end

describe('Serial', function()
  it('starts disconnected', function()
    local s = make()
    assert.is_false(s:isConnected())
    local ok, err = s:send('PING')
    assert.is_nil(ok)
    assert.same('no device connected', err)
  end)

  it('connects on attach, fires on update', function()
    local s, b = make()
    local info
    s:onConnect(function(i) info = i end, 'console')
    b:attach({ name = 'mb' })
    assert.is_true(s:isConnected())
    assert.is_nil(info)
    s:update()
    assert.same('mb', info.name)
  end)

  it('appends the terminator', function()
    local s, b = make()
    b:attach()
    assert.is_true(s:send('COMMAND 41 M 40 40 1000'))
    assert.same({ 'COMMAND 41 M 40 40 1000\n' }, b.sent)
  end)

  it('assembles lines across reads', function()
    local s, b = make()
    local got = {}
    s:onLine(function(l) got[#got + 1] = l end, 'console')
    b:attach()
    b:rx('ACK ')
    b:rx('41\nACK 42\n')
    s:update()
    assert.same({ 'ACK 41', 'ACK 42' }, got)
  end)

  it('passes raw chunks through', function()
    local s, b = make()
    local got = {}
    s:onBytes(function(c) got[#got + 1] = c end, 'console')
    b:attach()
    b:rx('AC')
    b:rx('K 41\n')
    s:update()
    assert.same({ 'AC', 'K 41\n' }, got)
  end)

  it('sends bytes before the lines built from them', function()
    local s, b = make()
    local order = {}
    s:onBytes(function() order[#order + 1] = 'b' end, 'console')
    s:onLine(function() order[#order + 1] = 'l' end, 'console')
    b:attach()
    b:rx('OK\n')
    s:update()
    assert.same({ 'b', 'l' }, order)
  end)

  it('drops a partial line on detach', function()
    local s, b = make()
    local got = {}
    s:onLine(function(l) got[#got + 1] = l end, 'console')
    b:attach()
    b:rx('PART')
    b:detach()
    b:attach()
    b:rx('OK\n')
    s:update()
    assert.same({ 'OK' }, got)
  end)

  it('reports disconnect', function()
    local s, b = make()
    local down = false
    s:onDisconnect(function() down = true end, 'console')
    b:attach()
    b:detach()
    s:update()
    assert.is_true(down)
    assert.is_false(s:isConnected())
  end)

  it('mutes a paused program, not the console', function()
    local s, b = make()
    local con, prg = {}, {}
    s:onLine(function(l) con[#con + 1] = l end, 'console')
    s:onLine(function(l) prg[#prg + 1] = l end)
    b:attach()
    s:programPaused()
    b:rx('A\n')
    s:update()
    assert.same({ 'A' }, con)
    assert.same({}, prg)
  end)

  it('resumes without replaying the gap', function()
    local s, b = make()
    local prg = {}
    s:onLine(function(l) prg[#prg + 1] = l end)
    b:attach()
    s:programPaused()
    b:rx('MISSED\n')
    s:update()
    s:programContinued()
    b:rx('B\n')
    s:update()
    assert.same({ 'B' }, prg)
  end)

  it('clears a paused program that ended', function()
    local s, b = make()
    local n = 0
    s:onLine(function() n = n + 1 end)
    s:programPaused()
    s:programEnded()
    s:onLine(function() n = n + 10 end)
    b:attach()
    b:rx('X\n')
    s:update()
    assert.same(10, n)
  end)

  it('keeps delivering after a handler fails', function()
    local s, b = make()
    local reached = false
    s:onLine(function() error('boom') end)
    s:onLine(function() reached = true end, 'console')
    b:attach()
    b:rx('X\n')
    local errors = s:update()
    assert.is_true(reached)
    assert.same(1, #errors)
  end)
end)

describe('Serial faults', function()
  it('reports overlong input through update', function()
    local b = FakeBackend.new()
    local s = Serial.new(b, 4)
    b:attach()
    b:rx('TOOLONG\n')
    local errors = s:update()
    assert.same(1, #errors)
    assert.same('serial', errors[1].env)
  end)
end)
