local h = love.harmony.utils or error()

local function editor()
  scenario('open-close', function(wait)
    wait(.1)
    h.love_text('project("test-create")')
    wait(.1)
    h.love_key('return')
    wait(.1)
    h.love_text('edit()')
    wait(.1)
    h.love_key('return')
    wait(.1)
    h.screenshot('open')
    wait(1)
    h.love_key('C-S-s')
    wait(.1)
    h.release_keys()

    wait(.1)
    h.love_text('list_contents()')
    wait(.1)
    h.love_key('return')
    wait(1)
    h.love_key('C-S-q')
    wait(.2)

    hm_done('edit')
  end)

  scenario('search', function(wait)
    wait(.1)
    h.love_text('project("turtle")')
    wait(.1)
    h.love_key('return')
    wait(.1)
    h.love_text('edit()')
    wait(.1)
    h.love_key('return')
    wait(.2)
    h.love_key('C-f')
    wait(.1)
    h.release_keys()
    h.screenshot('symbols')
    wait(.2)
    h.love_key('down')
    wait(.01)
    h.love_key('down')
    wait(.01)
    h.love_key('down')
    h.screenshot('symbols-2')

    wait(.1)
    h.love_text('draw')
    h.screenshot('symbols-3')
    wait(.5)
    h.love_key('backspace')
    wait(.01)
    h.love_key('backspace')
    wait(.01)
    h.love_key('backspace')
    wait(.01)
    h.love_key('backspace')
    wait(.2)
    h.love_text('tx')
    h.screenshot('symbols-4')
    wait(.2)

    h.love_key('return')
    wait(1)
    h.love_key('C-S-q')
    wait(1)

    hm_done()
  end)


  scenario('add', function(wait)
    wait(.1)
    h.love_text('project("test-add")')
    wait(.1)
    h.love_key('return')

    wait(.1)
    h.love_text('edit()')
    wait(.1)
    h.love_key('return')

    wait(.1)
    h.love_text('for i=1,5 do print(i) end')
    wait(.1)
    h.screenshot('input')
    wait(.1)
    h.love_key('return')

    wait(.1)
    h.screenshot('added')
    wait(.1)
    h.love_key('up')
    wait(.2)
    h.love_key('S-return')
    h.screenshot('newline')

    wait(1)
    h.love_key('C-S-q')
    wait(.1)
    h.release_keys()
    wait(.1)

    hm_done()
  end)

  scenario('change', function(wait)
    wait(.1)
    h.love_text('project("turtle")')
    wait(.1)
    h.love_key('return')

    wait(.1)
    h.love_text('edit("drawing.lua")')
    wait(.1)
    h.love_key('return')
    wait(.1)
    h.screenshot('open')
    wait(.2)
    h.love_key('f8')

    wait(2)

    wait(.1)
    h.screenshot('before')
    wait(.2)
    h.love_key('f8')
    wait(.2)
    h.love_key('C-home')
    wait(.1)
    h.release_keys()
    wait(.1)
    h.screenshot('start')


    wait(.1)
    h.love_key('C-f')
    wait(.01)
    h.release_keys()
    wait(.1)
    h.love_text('body')
    wait(.01)
    h.love_key('return')

    wait(.1)
    h.love_key('escape')
    wait(.1)
    h.love_key('end')
    wait(.1)
    h.love_key('backspace')
    wait(.02)
    h.love_key('backspace')
    wait(.02)
    h.love_key('backspace')
    wait(.02)
    h.love_key('backspace')
    wait(.02)
    h.love_key('backspace')

    wait(.1)
    h.love_text('red')
    wait(.01)
    h.love_key('return')

    wait(.1)
    h.screenshot('edited')
    wait(.2)
    h.love_key('f8')
    wait(.1)
    h.screenshot('after')

    wait(1)
    h.love_key('C-S-q')
    wait(.1)
    h.release_keys()
    wait(.1)

    hm_done()
  end)
end

editor()
