--- these are for undocumented Love APIs

--- @class Handlers
--- @field update function?
--- @field draw function?
--- @field keypressed function?
--- @field keyreleased function?
--- @field textinput function?
--- @field mousemoved function?
--- @field mousepressed function?
--- @field mousereleased function?
--- @field wheelmoved function?
--- @field touchmoved function?
--- @field touchpressed function?
--- @field touchreleased function?
--- bespoke
--- @field singleclick function?
--- @field doubleclick function?
