name: Package

on: [push, pull_request]

env:
  PRODUCT_NAME: LOVEputer
  BUNDLE_ID: com.example.loveputer
  BUILD_TYPE: ${{ fromJSON('["dev", "release"]')[startsWith(github.ref, 'refs/tags/v')] }}
  OUTPUT_FOLDER: dist
  ARTIFACT_FOLDER: artifact
  LOVE_ARTIFACT_NAME: loveputer.love

jobs:
  build-love:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build bare love package
        uses: love-actions/love-actions-core@v1
        with:
          build-list: "./src/*"
          package-path: ${{ env.OUTPUT_FOLDER }}/${{ env.LOVE_ARTIFACT_NAME }}
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.LOVE_ARTIFACT_NAME }}
          path: ${{ env.OUTPUT_FOLDER }}/${{ env.LOVE_ARTIFACT_NAME }}

  # build-android:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: love-actions/love-actions-android@v1

  build-linux:
    runs-on: ubuntu-latest
    needs: build-love
    steps:
      - uses: actions/checkout@v3
      - name: Download love package
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.LOVE_ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_FOLDER }}/
      - name: Build Linux packages
        env:
          ACTIONS_STEP_DEBUG: true
        id: build-packages
        uses: love-actions/love-actions-linux@v1
        with:
          app-name: ${{ env.PRODUCT_NAME }}
          bundle-id: ${{ env.BUNDLE_ID }}
          love-package: ${{ env.ARTIFACT_FOLDER }}/${{ env.LOVE_ARTIFACT_NAME }}
          product-name: ${{ env.PRODUCT_NAME }}
          output-folder: ${{ env.OUTPUT_FOLDER }}
          icon-path: ./assets/example_icon.png
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.OUTPUT_FOLDER }}

  release:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs:
      - build-love
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: ${{ env.ARTIFACT_FOLDER }}
      - name: Checksums
        run: |
          cd artifacts
          sha256sum * > SHA256SUMS.txt
      - uses: sigstore/gh-action-sigstore-python@v1.2.3
        with:
          inputs: ${{ env.ARTIFACT_FOLDER }}/*
      - name: control
        run: ls ${{ env.ARTIFACT_FOLDER }}/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
