name: Package

on: [push, pull_request]

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nhartland/love-build@master
        with:
          app_name: "hello_world"
          love_version: "11.4"
          source_dir: "src/"
      - name: control
        run: ls -lR
      - uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: "release/"

  release:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs:
      - build-package
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifacts/
      - name: Checksums
        run: |
          cd artifacts
          sha256sum * > SHA256SUMS.txt
      - uses: sigstore/gh-action-sigstore-python@v1.2.3
        with:
          inputs: artifacts/*
      - name: control
        run: ls artifacts/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
